.TH MAT2 "1" "July 2018" "MAT2 0.2.0" "User Commands"

.SH NAME
mat2 \- the metadata anonymisation toolkit 2

.SH SYNOPSIS
mat2 [\-h] [\-v] [\-l] [\-c] [\-s | \-L]\fR [files [files ...]]

.SH DESCRIPTION
.B mat2
removes metadata from various fileformats. It supports a wide variety of file 
formats, audio, office, images, …

.SH OPTIONS
.SS "positional arguments:"
.TP
\fBfiles\fR
the files to process
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-l\fR, \fB\-\-list\fR
list all supported fileformats
.TP
\fB\-c\fR, \fB\-\-check\-dependencies\fR
check if MAT2 has all the dependencies it needs
.TP
\fB\-s\fR, \fB\-\-show\fR
list harmful metadata detectable by MAT2 without
removing them
.TP
\fB\-L\fR, \fB\-\-lightweight\fR
remove SOME metadata

.SH EXAMPLES
To remove all the metadata from a PDF file:
.PP
.nf
.RS
mat2 ./myfile.pdf
.RE
.fi
.PP

.SH BUGS

While mat2 does its very best to remove every single metadata,
it's still in beta, and \fBsome\fR might remain. Should you encounter
some issues, check the bugtracker: https://0xacab.org/jvoisin/mat2/issues
.PP
Please use accordingly and be careful.

.SH AUTHOR
This software was made by Julien (jvoisin) Voisin with the support of the Tails project.

.SH COPYRIGHT
This software is released on LGPLv3.

.SH "SEE ALSO"
.BR exiftool (1p)
.BR pdf-redact-tools (1)
